#!/bin/bash
#PBS -l nodes=1:ppn=8,walltime=6:00:00
#PBS -N mrtrix3_act
#PBS -V

module load singularity 2> /dev/null

## container version
tag=3.0_RC2

echo "Processing tractography files..."
time singularity exec -e docker://brainlife/mrtrix3:$tag ./mrtrix3_segment.sh
