#!/bin/bash
#PBS -l nodes=1:ppn=8,walltime=14:00:00
#PBS -N bl_mrtrix3_preproc
#PBS -V

module load singularity 2> /dev/null

## container version
tag=3.0_RC2

echo "Preprocessing data..."
time singularity exec -e docker://brainlife/mrtrix3:$tag ./mrtrix3_ROI2ROI_track.sh
